/**
 * Offline-first build: after `vite build`, writes `sw.js` into the output
 * folder with every built file in its precache list. Open the deck online
 * once and the service worker keeps the whole thing for the flight.
 *
 * The cache name is a hash of the files (and of the worker itself), so every
 * deploy that changes anything installs a fresh copy and drops the old one.
 */
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { join, relative, resolve, sep } from 'node:path'

const SW = 'sw.js'

function walk(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walk(join(dir, e.name)) : [join(dir, e.name)],
  )
}

/** @returns {import('vite').Plugin} */
export function offline() {
  let outDir = 'dist'
  return {
    name: 'deck-offline',
    apply: 'build',
    configResolved(config) {
      outDir = resolve(config.root, config.build.outDir)
    },
    closeBundle() {
      const hash = createHash('sha256')
      const files = walk(outDir)
        .map((f) => relative(outDir, f).split(sep).join('/'))
        .filter((f) => f !== SW && !f.endsWith('.DS_Store'))
        .sort()
      hash.update(serviceWorker('', files))
      for (const f of files) hash.update(f).update(readFileSync(join(outDir, f)))
      const version = hash.digest('hex').slice(0, 12)
      writeFileSync(join(outDir, SW), serviceWorker(version, files))
    },
  }
}

const serviceWorker = (version, files) => `// Generated by scripts/offline.mjs — do not edit.
const CACHE = 'deck-${version}'
const FILES = ${JSON.stringify(files, null, 2)}
const INDEX = new URL('index.html', self.registration.scope).href

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      .then((cache) => cache.addAll(FILES.map((f) => new Request(f, { cache: 'reload' }))))
      .then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('deck-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

// Cache first: the deck never changes between deploys, and a new deploy
// ships a new sw.js that re-caches everything. ignoreVary: module scripts
// carry an Origin header the precache requests did not, and a server that
// answers \`Vary: Origin\` would otherwise miss every one of them offline.
self.addEventListener('fetch', (event) => {
  const { request } = event
  if (request.method !== 'GET' || new URL(request.url).origin !== self.location.origin) return
  event.respondWith(
    caches.open(CACHE).then(async (cache) => {
      const hit =
        (await cache.match(request, { ignoreSearch: request.mode === 'navigate', ignoreVary: true })) ??
        (request.mode === 'navigate' ? await cache.match(INDEX, { ignoreVary: true }) : undefined)
      return hit ?? fetch(request)
    }),
  )
})
`
